import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Change App Language': 'Change App Language',
          'Driver Login': 'Driver Login',
          'OR': 'OR',
          'Your_Name': 'Your_Name',
          'Your_Password': 'Your_Password',
          'Vehicle Information': 'Vehicle Information',
          'Your_Email': 'Your_Email',
          'SIGN UP': 'SIGN UP',
          'SIGN IN': 'SIGN IN',
          ' LOGIN': ' LOGIN',
          " SIGNUP": ' SIGNUP',
          'Sign Up': 'Sign Up',
          'Please signup to continue': 'Please signup to continue',
          'Add Profile Picture': 'Add Profile Picture',
          'Full Name': 'Full Name',
          'Type a password': 'Type a password',
          'Email': 'Email',
          'Password': 'Password',
          'Create Password': 'Create password',
          'Phone Number': 'Phone Number',
          'Forgot Password?': 'Forgot Password?',
          "Do not Have an Account? ": 'Dont have any account?',
          'Enter your Vehicle Information': 'Enter your Vehicle Information',
          'Add Your vehicle Image': 'Add Your vehicle Image',
          'Company Title': 'Company Title',
          'Engine Number': 'Engine Number',
          'Registration Number': 'Registration Number',
          'Car Design': 'Car Design',
          'Chassis Number': 'Chassis Number',
          'If you want to work as driver for us,':
              'If you want to work as driver for us,',
          'you have to come to office to make a':
              'you have to come to office to make a',
          'partner contract.': 'partner contract.',
          'Soon you’ll Receive Mail and SMS': 'Soon youll Receive Mail and SMS',
          'with details': 'with details',
          'OKAY': 'OKAY',
          'Already have an account': 'Already have an account',
          'Hours Online': 'Hours Online',
          'Total Distance': 'Total Distance',
          'Total Jobs': 'Total Jobs',
          'Logout': 'Logout',
          'Level Info': 'Level Info',
          'Mongolian': 'Mongolian',
          'English': 'English',
          'Language': 'Language',
          'Notifications': 'Notifications',
          'History': 'History',
          'Accept': 'Accept',
          'REJECT': 'REJECT',
          'My Wallet': 'My Wallet',
          'Home': 'Home',
          'Chat': 'Chat',
          'Chats': 'Chats',
          'My wallet': 'My wallet',
          'Current Balance': 'Current Balance',
          'Net Income': 'Net Income',
          'Withdrawn': 'Withdrawn',
          'Available for Withdrawal': 'Available for Withdrawal',
          'Order History': 'Order History',
          'COMPLETE': 'COMPLETE',
          'CANCEL': 'CANCEL',
          'No Completed Orders': 'No Completed Orders',
          'No Cancelled Orders': 'No Cancelled Orders',
          'SUBMIT': 'SUBMIT',
          'Describe your Issue here': 'Describe your Issue here',
          'Report an issue': 'Report an issue',
          'Enter your Order Id here': 'Enter your Order Id here',
          'Order ID': 'Order ID',
          'No Notifications Found': 'No Notifications Found',
          'Please How we can help you?': 'Please How we can help you?',
          'Help And Support': 'Help And Support',
          'Select your Issue': 'Select your Issue',
          'Issue Regarding Product Damage': 'Issue Regarding Product Damage',
          'Product Misplace': 'Product Misplace',
          'Late Delivery': 'Late Delivery',
          'Bad user experience': 'Bad user experience',
          'Help & Support': 'Help & Support',
          'Save': 'Save',
          'Yes': 'Yes',
          'Success': 'Success',
          'Error': 'Error',
          'Your email address is invalid': 'Your email address is invalid',
          'Levels': 'Levels',
          'CONGRATS': 'CONGRATS',
          'YOU ARE NOW LEVEL ONE DRIVER': 'YOU ARE NOW LEVEL ONE DRIVER',
          'Level One': 'Level One',
          'Level Two': 'Level Two',
          'Level Three': 'Level Three',
          'Top High Rated': 'Top High Rated',
          'YOU ARE NOW LEVEL TWO DRIVER': 'YOU ARE NOW LEVEL TWO DRIVER',
          'YOU ARE NOW LEVEL THREE DRIVER': 'YOU ARE NOW LEVEL THREE DRIVER',
          'Password is required': 'Password is required',
          'Password should be at least six digits.':
              'Password should be at least six digits.',
          'Email is required': 'Email is required',
          'Your password is wrong.': 'Your password is wrong.',
          'User with this email does not exist.':
              'User with this email does not exist.',
          'User with this email has been disabled':
              'User with this email has been disabled',
          'Too many requests': 'Too many requests',
          'Signing in with Email and Password is not enabled.':
              'Signing in with Email and Password is not enabled.',
          'An undefined Error happened': 'An undefined Error happened',
          "Email already exist, kindly try some one else":
              "Email already exist, kindly try some one else",
          'Account Created Successfully!!': 'Account Created Successfully!!',
          'Required': 'Required',
          'PROFILE': 'PROFILE',
          'Verified Driver': 'Verified Driver',
          'Address': 'Address',
          'Update': 'Update',
          '50  (Reviews)': '50  (Reviews)',
          'Order Price': 'Order Price',
          'Distance:': 'Distance:',
          'Time:': 'Time:',
          'Weight': 'Weight',
          'Parcel Name': 'Parcel Name',
          'View Details': 'View Details',
          'Type your Message...': 'Type your Message...',
          'Order Details': 'Order Details',
          'PICKUP DETAILS': 'PICKUP DETAILS',
          'DELIVERY DETAILS': 'DELIVERY DETAILS',
          'Parcel Description': 'Parcel Description',
          'SUB TOTAL': 'SUB TOTAL',
          'TOTAL': 'TOTAL',
          'ORDER ID': 'ORDER ID',
          'Order Chat': 'Order Chat',
          'PICKUP AT LOCATION': 'PICKUP AT LOCATION',
          'DELIVER AT LOCATION': 'DELIVER AT LOCATION',
          'Send FeedBack': 'Send FeedBack',
          'Order Completed': 'Order Completed',
          'Order Complete': 'Order Complete',
          'Pickup Location': 'Pickup Location',
          'You Reached PickUp location': 'You Reached PickUp location',
          'Delivery Location': 'Delivery Location',
          'You Reached Delivery location': 'You Reached Delivery location',
          'Enter OTP' : 'Enter OTP',
          'Verify OTP' : 'Verify OTP',
          'RESEND OTP' : 'RESEND OTP',
          'Please try again' : 'Please try again',
          'Invalid Otp' : 'Invalid Otp',
        },
        
        'mn_MN': {
          'Invalid Otp' : 'Хүчингүй',
          'Please try again' : 'Дахин оролдоно',
          'RESEND OTP' : 'ДАХИН ИЛГЭЭХ',
          'Verify OTP' : 'Баталгаажуулах',
          'Enter OTP' : 'OTP оруулна',
          'Change App Language': 'Програмын хэлийг өөрчлөх',
          'SIGN IN': 'НЭВТРҮҮЛЭХ',
          'Driver Login': 'Жолооч нэвтрэх',
          'OR': 'ЭСВЭЛ',
          'Your_Name': 'taны_эP',
          'Your_Password': 'Таны нууц ',
          'VEHICLE INFORMATION': 'Тээврийн хэрэгслийн мэдээлэл',
          'Your_Email': 'Таны имэйл',
          "Sign Up": ' БҮРТГҮҮЛЭХ',
          'SIGN UP': 'БҮРТГҮҮЛЭХ',
          " SIGNUP": ' БҮРТГҮҮЛЭХ',
          'LOGIN': 'НЭВТРЭХ',
          ' LOGIN': ' НЭВТРЭХ',
          'Please signup to continue': 'Үргэлжлүүлэхийн тулд бүртгүүлнэ ',
          'Add Profile Picture': 'Профайл зураг нэмэх',
          'Full Name': 'Бүтэн нэр',
          'Your name': 'Таны нэр',
          'Email': 'Имэйл',
          'Notifications': 'Мэдэгдэл',
          'Password': 'Нууц yr',
          'Your email': 'Таны имэйл',
          'Create Password': 'Шинэ нууц үүсгэх',
          'Type a strong password': 'Хүчтэй нууц оруулна ',
          'Type a password': 'Нууц оруулна ',
          'Phone Number': 'Утасны дугаар',
          'Please Login to continue': 'Үргэлжлүүлэхийн тулд нэвтэрнэ ',
          'Forgot Password?': 'Нууц үгээ мартсан ?',
          "Do not Have an Account? ": 'Ямар ч данс байхгүй юу?',
          'Already Have an Account? ': 'Бүртгэлтэй юу?',
          'Password is required': 'нууц шаардлагатай',
          'Password should be at least six digits.':
              'Нууц дор хаяж зургаан оронтой байх ёстой.',
          'Email is required': 'Имэйл шаардлагатай',
          'Already have an account': 'Бүртгэлтэй болсон байна',
          'Enter your Vehicle Information':
              'Тээврийн хэрэгслийнхээ мэдээллийг оруулна',
          'Add Your vehicle Image': 'Өөрийн тээврийн хэрэгслийн зургийг нэмнэ',
          'Company Title': 'Компанийн нэр',
          'Engine Number': 'Хөдөлгүүрийн дугаар',
          'Registration Number': 'Регистрийн дугаар',
          'Car Design': 'Машины дизайн',
          'Chassis Number': 'Явах эд ангийн дугаар',
          'If you want to work as driver for us,':
              'манайд жолоочоор ажиллахыг хүсвэл',
          'you have to come to office to make a':
              'хийхийн тулд оффис дээр ирэх ёстой',
          'partner contract.': 'түншийн гэрээ.',
          'Soon you’ll Receive Mail and SMS':
              'Удалгүй та шуудан болон SMS хүлээн авах болно',
          'with details': 'дэлгэрэнгүй мэдээлэлтэй',
          'OKAY': 'болж байна',
          'Hours Online': 'Онлайнаар ажиллах цаг',
          'Total Distance': 'Нийт зай',
          'Total Jobs': 'Нийт ажлын байр',
          'Level Info': 'Түвшингийн мэдээлэл',
          'History': 'түүх',
          'Accept': 'Зөвшөөрөх',
          'REJECT': 'ТАТГАЛЗАХ',
          'My Wallet': 'Миний түрийвч',
          'Chat': 'Чатлах',
          'Chats': 'Чат',
          'My wallet': 'Миний түрийвч',
          'Current Balance': 'Одоогийн үлдэгдэл',
          'Net Income': 'Нийт орлого',
          'Withdrawn': 'Татан авсан',
          'Available for Withdrawal': 'Татгалзах боломжтой',
          'Order History': 'Захиалгын түүх',
          'COMPLETE': 'БҮРЭН БАЙНА',
          'CANCEL': 'Цуцлах',
          'No Completed Orders': 'Дууссан захиалга байхгүй',
          'No Cancelled Orders': 'Цуцлагдсан захиалга байхгүй',
          'SUBMIT': 'ИЛГЭЭХ',
          'Describe your Issue here': 'Асуудлаа энд тайлбарлана y',
          'Report an issue': 'Асуудлыг мэдээлэх',
          'Enter your Order Id here': 'Захиалгын дугаараа энд оруулна y',
          'Order ID': 'Захиалгын ID',
          'Please How we can help you?': 'Бид танд хэрхэн туслах вэ?',
          'Help And Support': 'Тусламж дэмжлэг',
          'Select your Issue': 'Асуудлаа сонгоно',
          'Issue Regarding Product Damage':
              'Бүтээгдэхүүний гэмтэлтэй холбоотой асуудал',
          'Product Misplace': 'Бүтээгдэхүүний газар',
          'Late Delivery': 'Хожуу хүргэлт',
          'Bad user experience': 'Хэрэглэгчийн муу туршлага',
          'Help & Support': 'Тусламж дэмжлэг',
          'Home': 'Гэр',
          'Language': 'Хэл',
          'English': 'Англи',
          'Mongolian': 'Монгол',
          'Logout': 'Гарах',
          'Ok': 'Болж байна ',
          'Cancel': 'Цуцлах',
          'Do you want to Logout?': 'гарахыг хүсэж байна?',
          'LOGOUT': 'ГАРАХ',
          'Address': 'Хаяг',
          'EDIT PROFILE': 'засварлах Хувийн мэдээллийг',
          'Profile': 'Профайл',
          'Save': 'Хадгалах',
          'Enter Email': 'Имэйл оруулна ',
          'Enter Phone Number': 'Утасны дугаар оруулна ',
          'Enter Name': 'Нэрийг оруулна ',
          'Name': 'Нэр',
          'How’s Your Order?  Feedback Please':
              'Таны захиалга ямар байна? Санал хүсэлт өгнө ',
          'SEND FEEDBACK': 'САНАЛ ИЛГЭЭХ',
          'Success': 'Тиймээ',
          'Error': 'Алдаа',
          'Your email address is invalid': 'Таны имэйл хаяг  байна',
          'Your password is wrong.': 'Таны нууц  байна.',
          'User with this email does not exist.':
              'Энэ имэйлтэй хэрэглэгч байхгүй байна.',
          'User with this email has been disabled':
              'Энэ имэйлтэй хэрэглэгч идэвхгүй болсон',
          'Too many requests': 'Хэт олон хүсэлт',
          'Signing in with Email and Password is not enabled.':
              'Имэйл болон нууц үгээр нэвтрэхийг идэвхжүүлээгүй байна.',
          'An undefined Error happened': 'Тодорхойгүй алдаа гарлаа',
          "Email already exist, kindly try some one else":
              "Имэйл аль хэдийн байгаа тул өөр хаягаар оролдоно ",
          'Account Created Successfully!!': 'Бүртгэлийг амжилттай үүсгэсэн!!',
          'Feedback Sent Successfully!': 'Санал хүсэлтийг амжилттай илгээлээ!',
          'Please enter orderId': 'Захиалгын дугаар оруулна',
          'Please add rating': 'Үнэлгээ нэмнэ ',
          'Required': 'Шаардлагатай',
          'Levels': 'Түвшин',
          'CONGRATS': 'БАЯР ХҮРГЭЕ',
          'YOU ARE NOW LEVEL ONE DRIVER':
              'ОДОО НЭГДҮГЭЭР ТҮВШНИЙ ЖОЛООЧ БОЛЛОО',
          'Level One': 'Нэгдүгээр түвшин',
          'Level Two': 'Хоёрдугаар түвшин',
          'Level Three': 'Гуравдугаар түвшин',
          'Top High Rated': 'Хамгийн өндөр үнэлгээтэй',
          'YOU ARE NOW LEVEL TWO DRIVER':
              'ОДОО ХОЁРДУГААР ТҮВШНИЙ ЖОЛООЧ БАЙНА',
          'YOU ARE NOW LEVEL THREE DRIVER':
              'ОДОО ГУРАВДУГААР ТҮВШНИЙ ЖОЛООЧ БОЛЛОО',
          'PROFILE': 'PROFILE',
          'Verified Driver': 'Баталгаажсан жолооч',
          'Update': 'Шинэчлэх',
          '50  (Reviews)': '50 (Шүүмж)',
          'Order Price': 'Захиалгын үнэ',
          'Distance:': 'Зай:',
          'Time:': 'Цаг хугацаа:',
          'Weight': 'Жин',
          'Parcel Name': 'Илгээмжийн нэр',
          'View Details': 'Дэлгэрэнгүй мэдээллийг',
          'Order Chat': 'Чатаар захиалаарай',
          'Order Details': 'захиалгын мэдээлэл',
          'PICKUP DETAILS': 'ДЭЛГЭРЭНГҮЙ',
          'DELIVERY DETAILS': 'ХҮРГЭЛТИЙН ДЭЛГЭРЭНГҮЙ',
          'Parcel Description': 'Илгээмжийн тодорхойлолт',
          'SUB TOTAL': 'ДЭД НИЙТ',
          'TOTAL': 'НИЙТ',
          'ORDER ID': 'ЗАХИАЛАХ ID',
          'PICKUP AT LOCATION': 'БАЙРШЛАГАА',
          'DELIVER AT LOCATION': 'БАЙРШЛААР ХҮРГҮҮЛНЭ',
          'Type your Message...': 'Мессежээ бичнэ...',
          'Send FeedBack': 'Санал илгээх',
          'Order Completed': 'Захиалга дууссан',
          'Order Complete': 'Захиалга дууссан',
          'Pickup Location': 'Татаж авах газар',
          'You Reached PickUp location': 'хүлээн авах байршилд хүрлээ',
          'Delivery Location': 'Хүргэлтийн байршил',
          'You Reached Delivery location': 'хүргэлтийн байршилд хүрлээ',
        }
      };
}
